"""add payment_details to sales

Revision ID: 29c5d8ccdbfa
Revises: d1dea287ad09
Create Date: 2026-08-09 20:28:15.820158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29c5d8ccdbfa'
down_revision: Union[str, Sequence[str], None] = 'd1dea287ad09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
