"""payment_detaile_sust_cash_trasnferreceibe

Revision ID: 9c7cc0c9f8b3
Revises: abf1d53a303b
Create Date: 2026-08-10 04:42:17.603218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7cc0c9f8b3'
down_revision: Union[str, Sequence[str], None] = 'abf1d53a303b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('payment_details', sa.JSON(), nullable=False))
    op.add_column('sales', sa.Column('payment_methods', sa.JSON(), nullable=True))
    op.drop_column('sales', 'cash_received')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('cash_received', sa.FLOAT(), nullable=False))
    op.drop_column('sales', 'payment_methods')
    op.drop_column('sales', 'payment_details')
    # ### end Alembic commands ###
