"""payment_detaile_sust_cash_trasnferreceibe

Revision ID: eb9fac0295b1
Revises: 9c7cc0c9f8b3
Create Date: 2026-08-10 04:43:22.311048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9fac0295b1'
down_revision: Union[str, Sequence[str], None] = '9c7cc0c9f8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
